name: Vac
title: Vac
title_image: "/assets/img/vac.jpg"
description: >- # this means to ignore newlines until "baseurl:"
  Vac is a modular peer-to-peer messaging stack, with a focus on secure messaging.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vac.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vacp2p
github_username:  vacp2p

# Build settings
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true